# Generated by Django 5.0.7 on 2024-07-20 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='topic',
            new_name='subject',
        ),
    ]
