# Generated by Django 5.0.7 on 2024-07-20 15:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_topic_contact_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='Anonymous')),
                ('cv', models.FileField(default='default_files/default_face.jpg', upload_to='account_files/profile_photos/')),
                ('email', models.CharField(default='', max_length=2000)),
                ('phone', models.CharField(default='', max_length=1000)),
                ('address', models.CharField(default='', max_length=2000)),
                ('start_date', models.CharField(default='', max_length=2000)),
                ('position', models.CharField(default='', max_length=2000)),
                ('qualification', models.TextField(default='', max_length=11130, null=True)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
